os: linux
dist: jammy
language: python
python:
  - '3.8'

install: true

# build only the master branch or tags like #.#.#
branches:
  only:
    - master
    - /^[0-9]+(\.[0-9]+){2}$/

# split jobs and only re-execute the failing one
jobs:
  fast_finish: true
  include:

    - name: "Test library"
      stage: test
      script: ./scripts/travis_test.sh
      if: type = pull_request
      python:
        - '3.10'

    - name: "Test release"
      stage: test
      script: ./scripts/travis_release.sh
      if: type = pull_request

    - name: "Release"
      stage: deploy
      script: ./scripts/travis_release.sh
      # release only if tag like #.#.# (never in forks or pull requests)
      if: |
        fork IS false AND \
        type != pull_request AND \
        (tag =~ ^[0-9]+(\.[0-9]+){2}$)
