os: linux
dist: jammy
language: python
python:
  - '3.10'

install: true
env:
  global:
    # Workaround for issue with setuptools
    - SETUPTOOLS_USE_DISTUTILS=stdlib

# build only the master branch or tags like #.#.#
branches:
  only:
    - master
    - /^[0-9]+(\.[0-9]+){2}$/

# split jobs and only re-execute the failing one
jobs:
  fast_finish: true
  include:

    - name: "Test"
      stage: test
      script: ./scripts/travis_test.sh

    - name: "Release"
      stage: deploy
      script: ./scripts/travis_release.sh
      # release only if tag like #.#.# (never in forks or pull requests)
      if: |
        fork IS false AND \
        type != pull_request AND \
        (tag =~ ^[0-9]+(\.[0-9]+){2}$)
