sudo: required
language: python
python:
  - '3.6'

install: true

# use matrix to split jobs and only re-execute the failing one
matrix:
  fast_finish: true
  include:
    - name: "Test"
      stage: test
      install: ./scripts/install.sh
      script: ./scripts/test.sh && ./scripts/build.sh

    - name: "Release"
      stage: deploy
      # TODO
      script: echo "releasing..."
      # release only if tag like #.#.#
      if: (tag =~ ^[0-9]+(\.[0-9]+){2}$)
