dist: xenial
language: python
python:
  - '3.7'

install: true

# use matrix to split jobs and only re-execute the failing one
matrix:
  fast_finish: true
  include:

    - name: "Test"
      stage: test
      script: ./scripts/travis_test.sh

    - name: "Release"
      stage: deploy
      script: ./scripts/travis_release.sh
      # release only if tag like #.#.#
      if: (tag =~ ^[0-9]+(\.[0-9]+){2}$)
