sudo: required
language: python
python:
  - '3.6'

services:
  - docker

install: true

# use matrix to split jobs and only re-execute the failing one
matrix:
  fast_finish: true
  include:
    - name: "Test"
      stage: test
      script: ./build.sh

    # execute only to deploy
    - name: "Release"
      stage: deploy
      # TODO
      script: ./release.sh
      # release only if tag like #.#.#
      if: (tag =~ ^[0-9]+(\.[0-9]+){2}$)
