# Generated by Django 2.2.7 on 2019-11-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cas', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='userrole',
            constraint=models.UniqueConstraint(
                fields=('user', 'group'),
                name='unique_user_and_role',
            ),
        ),
    ]
