version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:

  test:
    description: "Test library and push library package to TestPyPi repository"
    executor: python/default
    steps:
      - checkout
      - run: ./.circleci/ci_test.sh

  release:
    description: "Push new library package to PyPi repository"
    executor: python/default
    steps:
      - checkout
      - run: ./.circleci/ci_release.sh

workflows:
  version: 2
  test-and-release:
    description: "Tests and release"
    jobs:
      - test
      - release:
          # if tests successful
          requires:
            - test
          filters:
            # release only in:
            #   tag #.#.#
            branches:
              ignore: /.*/
            tags:
              only: /^[0-9]+(\.[0-9]+){2}$/
